name: Repository Mirroring

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Mirror Pushing
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        env:
          GITHUB_SSH_KEY_PRIVATE: ${{ secrets.GITHUB_SSH_KEY_PRIVATE}}
        with:
          target_repo_url: git@github.com:blacky-yg/workflow_mirror.git
          ssh_private_key: ${{ secrets.GITHUB_SSH_KEY_PRIVATE }}
        run: echo GITHUB_SSH_KEY_PRIVATE
