name: Repository Size

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Display the current branch
        run: echo ${GITHUB_REF##*/}
      - name: Check the repository size
        run: du -skh --exclude=".git"
